### ISSUE TITLE
Linux命令行登录OceanBase输入use命令导致键盘异常

### ISSUE THREAD

**Issue by ynzzxc** [oceanbase/obclient#8]
系统：Ubuntu 18.04.5 LTS
OceanBase版本：开源3.1.1
obclient版本：2.0.0-2

问题描述：
登录数据库  obclient -h *** -P2883 -uroot@sys；
输入命令 use；
然后敲击delete、Backspace、Ctrl+delete、Ctrl+backspace、方向键等均会打出空格，最多能打出4个空格；把键序列改成ASCII127之后，敲击delete、Backspace、Ctrl+delete、Ctrl+backspace会打出乱码字符。

**Comment by longdafeng** [comment]
你这个有点诡异, 你换mysql 客户端有这个问题吗?

**Comment by ynzzxc** [comment]
> 你这个有点诡异, 你换mysql 客户端有这个问题吗?

测试了一下，换mysql客户端没出现异常

**Comment by longdafeng** [comment]
ok, 我们来看一下

**Comment by ynzzxc** [comment]
> ok, 我们来看一下

感谢！
